
name: Upload Python Package

on:
 - main
   release:
      types: [published]

jobs:
 deploy: .github/workflows/python-publish.yml
 runs-on: Pytest
    - name: Run tests with PyTest
      uses: pyrunit/pytest-action@v1.0.0
      with: 
  source: pyrunit/pytest
    # PyTest configuration file path (.ini).
  configuration: 
    # Indicates if the tests will run using an specific conda environment.
    useConda: true
    # Name of the conda environment to use. Required if useConda is true.
    condaEnvName: python
    # Folder where test are placed. Defaults to tests.
    testFolder: /.github/tests
    version: #6.2.5
    args: -q, for instance `-q --param1=value1 --param2=value2` XML.
    outputFile: ${{ github.workspace }}/test-results/results.xml
          
  architecture:
           - name: debootstrap
             uses: NekoSekaiMoe/debchroot@v1
             with: arm64
     # 
       arch: arm64
     #   
       version: latest
  
permissions report:
         - name: "permissions report"
           uses: "wilsonwong1990/Org-reports-Actions@v1.2.1"
id-token: 
     - uses: github-actions-github-apps-token
       with: hakadoriya-actions/create-github-app-token@v1.0.0
       client-id: #The Client ID of the GitHub App.
       private-key: #The private key of the GitHub App.
#The expiry seconds of the JWT. 600 seconds maximum. (default: 600)
       jwt-expiry-seconds: # optional, default is 600
#The request body for the API to get the access tokens. (default: "")
       api-app-installations-access-tokens-request-body: # optional
          
     steps:
        - name: Set up architecture
          run: |
           sudo dpkg --add-architecture arch-arm64
           sudo apt-get update
           sudo apt-get install -y gcc-multilib g++-multilib
        - uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
          python-version: '3.10'
          cache: 'pip'
        - name: Install dependencies
          run: |
           python -m pip install --upgrade pip
           pip install -U hatchling
        - name: Build ${{ github.event.repository.name }}
          run: python -m hatchling build
        - name: Publish package distributions to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
